# Generated by Django 3.0.6 on 2020-06-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profle_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
