# Generated by Django 3.0.6 on 2020-06-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_profle_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profle_pic',
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
